export const careersByCategory: Record<string, string[]> = {
  "Negocios y Economía": [
    "Administración",
    "Administración y Emprendimiento",
    "Administración y Finanzas Corporativas",
    "Digital Business Management",
    "Economía y Finanzas",
    "Economía y Negocios Internacionales",
    "International Business",
    "Marketing",
  ],
  "Ciencias de la Salud": [
    "Medicina Humana",
    "Psicología",
    "Nutrición y Dietética",
    "Enfermería",
    "Tecnología Médica en Terapia Física y Rehabilitación",
    "Ciencias de la Actividad Física y del Deporte",
  ],
  "Ingeniería y Tecnología": [
    "Ingeniería de Sistemas de Información",
    "Ingeniería de Software",
    "Ciencia de Datos",
    "Ingeniería Industrial y Comercial",
    "Ingeniería Civil",
    "Ingeniería Mecatrónica",
    "Ingeniería Ambiental",
    "Ingeniería Biomédica",
    "Ingeniería Agroindustrial",
    "Ingeniería en Ciberseguridad",
    "Ingeniería Empresarial",
    "Ingeniería en Industrias Alimentarias",
  ],
  "Comunicación y Turismo": [
    "Comunicación y Publicidad",
    "Comunicación y Periodismo",
    "Administración de Turismo",
    "Administración Hotelera",
    "Gastronomía y Gestión Culinaria",
    "Arte y Diseño Empresarial",
  ],
  "Derecho y Ciencias Políticas": ["Derecho", "Relaciones Internacionales"],
  "Humanidades y Educación": [
    "Educación Inicial",
    "Educación Primaria",
    "Educación de la Primera Infancia",
    "Educación con especialidad en Ciencias y Humanidades",
  ],
}
